### ISSUE TITLE
Does the sql database work with microsoft sql server?

### ISSUE THREAD

**Issue by ShikharGhimire** [zgoethel/himalayan-database#1]
Hi there. Thank you for working and having this database. I am also working on creating tourism database of Nepal and I am on the process of doing it(Check out my tourismdata repo). I however have a question whether the sql file can be worked upon on Microsoft sql server? Please let me know. Also, if you need any contribution done here, I would love to help you. Thank you

**Comment by zgoethel** [comment]
Hi @ShikharGhimire,

This project does not have it's own database, but downloads a set of data as a Microsoft Visual FoxPro database from the following site:

https://www.himalayandatabase.com/downloads.html

There you can access the database files used by the Himalayan Database project.  The database format they use is vastly outdated, but I wish you the best of luck if you choose to pay a visit.

**Comment by ShikharGhimire** [comment]
Thanks !
